#!/usr/bin/env python3
"""Run one-hop corpus expansion from seed queries via OpenAlex."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import time
import urllib.parse
from collections import Counter, defaultdict
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

OPENALEX_BASE = "https://api.openalex.org"


def openalex_env_auth_params() -> Dict[str, str]:
    """Return OpenAlex `mailto` / `api_key` query params from the environment when set."""
    out: Dict[str, str] = {}
    mailto = (os.getenv("OPENALEX_MAILTO") or "").strip()
    if mailto:
        out["mailto"] = mailto
    api_key = (os.getenv("OPENALEX_API_KEY") or os.getenv("OPENALEX_KEY") or "").strip()
    if api_key:
        out["api_key"] = api_key
    return out


@dataclass
class SeedResolution:
    seed_id: str
    seed_kind: str
    query_text: str
    doi: str
    year: Optional[int]
    matched: bool
    match_reason: str
    openalex_id: str
    work_id: str
    title: str
    publication_year: Optional[int]
    cited_by_count: Optional[int]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--seed-file",
        default="corpus/expansion_seed_queries.jsonl",
        help="JSONL seed file generated by build_corpus.py",
    )
    parser.add_argument(
        "--output-dir",
        default="corpus/expansion",
        help="Directory for expansion outputs",
    )
    parser.add_argument(
        "--mailto",
        default="",
        help="Optional contact email for OpenAlex polite pool",
    )
    parser.add_argument(
        "--max-forward-per-seed",
        type=int,
        default=100,
        help="Cap citing works collected per resolved seed",
    )
    parser.add_argument(
        "--request-timeout-sec",
        type=float,
        default=30.0,
        help="HTTP timeout per request",
    )
    parser.add_argument(
        "--sleep-sec",
        type=float,
        default=0.12,
        help="Sleep between requests to avoid rate spikes",
    )
    return parser.parse_args()


def load_jsonl(path: Path) -> List[Dict]:
    rows = []
    with path.open("r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


def write_json(path: Path, payload) -> None:
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")


def write_jsonl(path: Path, rows: Iterable[Dict]) -> None:
    with path.open("w", encoding="utf-8") as fh:
        for row in rows:
            fh.write(json.dumps(row, ensure_ascii=True) + "\n")


def normalize_doi(doi: str) -> str:
    doi = (doi or "").strip()
    if not doi:
        return ""
    doi = doi.replace("https://doi.org/", "").replace("http://doi.org/", "")
    doi = doi.replace("doi.org/", "").replace("DOI:", "").strip()
    return doi


def to_work_id(openalex_id: str) -> str:
    # https://openalex.org/W123... -> W123...
    if not openalex_id:
        return ""
    return openalex_id.rstrip("/").split("/")[-1]


def api_get_json(path: str, params: Dict[str, str], timeout_sec: float, sleep_sec: float):
    q = dict(params)
    for key, value in openalex_env_auth_params().items():
        if key not in q:
            q[key] = value
    url = f"{OPENALEX_BASE}{path}?{urllib.parse.urlencode(q)}"
    raw = subprocess.check_output(
        ["curl", "-sS", "--max-time", str(int(timeout_sec)), url],
        text=True,
    )
    data = json.loads(raw)
    if sleep_sec > 0:
        time.sleep(sleep_sec)
    return data


def resolve_seed(seed: Dict, timeout_sec: float, sleep_sec: float) -> SeedResolution:
    seed_id = seed.get("seed_id", "")
    seed_kind = seed.get("seed_kind", "")
    query_text = seed.get("query_text", "")
    doi = normalize_doi(seed.get("doi", ""))
    year = seed.get("year")
    if isinstance(year, str) and year.isdigit():
        year = int(year)
    if not isinstance(year, int):
        year = None

    if doi:
        data = api_get_json(
            "/works",
            {"filter": f"doi:{doi}", "per-page": "1"},
            timeout_sec=timeout_sec,
            sleep_sec=sleep_sec,
        )
        results = data.get("results", [])
        if results:
            work = results[0]
            return SeedResolution(
                seed_id=seed_id,
                seed_kind=seed_kind,
                query_text=query_text,
                doi=doi,
                year=year,
                matched=True,
                match_reason="doi",
                openalex_id=work.get("id", ""),
                work_id=to_work_id(work.get("id", "")),
                title=work.get("display_name", ""),
                publication_year=work.get("publication_year"),
                cited_by_count=work.get("cited_by_count"),
            )

    if query_text:
        data = api_get_json(
            "/works",
            {"search": query_text, "per-page": "5"},
            timeout_sec=timeout_sec,
            sleep_sec=sleep_sec,
        )
        results = data.get("results", [])
        if results:
            # Prefer same-year candidates when available.
            pick = results[0]
            if year is not None:
                same_year = [r for r in results if r.get("publication_year") == year]
                if same_year:
                    pick = same_year[0]
            return SeedResolution(
                seed_id=seed_id,
                seed_kind=seed_kind,
                query_text=query_text,
                doi=doi,
                year=year,
                matched=True,
                match_reason="search",
                openalex_id=pick.get("id", ""),
                work_id=to_work_id(pick.get("id", "")),
                title=pick.get("display_name", ""),
                publication_year=pick.get("publication_year"),
                cited_by_count=pick.get("cited_by_count"),
            )

    return SeedResolution(
        seed_id=seed_id,
        seed_kind=seed_kind,
        query_text=query_text,
        doi=doi,
        year=year,
        matched=False,
        match_reason="unresolved",
        openalex_id="",
        work_id="",
        title="",
        publication_year=None,
        cited_by_count=None,
    )


def fetch_forward_citations(
    work_id: str,
    max_forward_per_seed: int,
    timeout_sec: float,
    sleep_sec: float,
) -> List[Dict]:
    if not work_id or max_forward_per_seed <= 0:
        return []
    per_page = min(max_forward_per_seed, 200)
    data = api_get_json(
        "/works",
        {"filter": f"cites:{work_id}", "per-page": str(per_page)},
        timeout_sec=timeout_sec,
        sleep_sec=sleep_sec,
    )
    return data.get("results", [])[:max_forward_per_seed]


def chunked(items: List[str], size: int) -> Iterable[List[str]]:
    for idx in range(0, len(items), size):
        yield items[idx : idx + size]


def fetch_works_by_ids(work_ids: List[str], timeout_sec: float, sleep_sec: float) -> List[Dict]:
    if not work_ids:
        return []
    results: List[Dict] = []
    for chunk in chunked(work_ids, 50):
        filt = "openalex:" + "|".join(chunk)
        data = api_get_json(
            "/works",
            {"filter": filt, "per-page": str(len(chunk))},
            timeout_sec=timeout_sec,
            sleep_sec=sleep_sec,
        )
        results.extend(data.get("results", []))
    return results


def work_to_candidate(work: Dict) -> Dict:
    source = (work.get("primary_location") or {}).get("source") or {}
    return {
        "openalex_id": work.get("id", ""),
        "work_id": to_work_id(work.get("id", "")),
        "title": work.get("display_name", ""),
        "doi": normalize_doi(work.get("doi", "")),
        "publication_year": work.get("publication_year"),
        "type": work.get("type", ""),
        "cited_by_count": work.get("cited_by_count"),
        "host_venue": source.get("display_name", ""),
        "is_oa": (work.get("open_access") or {}).get("is_oa"),
        "concepts_top": [
            {"display_name": c.get("display_name", ""), "score": c.get("score")}
            for c in (work.get("concepts") or [])[:5]
        ],
    }


def main() -> None:
    args = parse_args()
    seed_file = Path(args.seed_file)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    seeds = load_jsonl(seed_file)
    if args.mailto.strip() and not (os.getenv("OPENALEX_MAILTO") or "").strip():
        os.environ["OPENALEX_MAILTO"] = args.mailto.strip()

    resolutions: List[SeedResolution] = []
    for seed in seeds:
        try:
            res = resolve_seed(seed, timeout_sec=args.request_timeout_sec, sleep_sec=args.sleep_sec)
        except Exception as exc:  # noqa: BLE001
            res = SeedResolution(
                seed_id=seed.get("seed_id", ""),
                seed_kind=seed.get("seed_kind", ""),
                query_text=seed.get("query_text", ""),
                doi=normalize_doi(seed.get("doi", "")),
                year=seed.get("year") if isinstance(seed.get("year"), int) else None,
                matched=False,
                match_reason=f"error:{type(exc).__name__}",
                openalex_id="",
                work_id="",
                title="",
                publication_year=None,
                cited_by_count=None,
            )
        resolutions.append(res)

    write_jsonl(output_dir / "seed_resolutions.jsonl", [r.__dict__ for r in resolutions])

    resolved = [r for r in resolutions if r.matched and r.work_id]
    work_to_seed_ids: Dict[str, List[str]] = defaultdict(list)
    edge_map: Dict[str, set] = defaultdict(set)
    backward_work_ids: set = set()
    forward_works_collected: List[Dict] = []

    for res in resolved:
        # Load seed work to access referenced_works.
        try:
            seed_work_data = api_get_json(
                "/works",
                {"filter": f"openalex:{res.work_id}", "per-page": "1"},
                timeout_sec=args.request_timeout_sec,
                sleep_sec=args.sleep_sec,
            )
            seed_results = seed_work_data.get("results", [])
            if seed_results:
                seed_work = seed_results[0]
                for ref_id in seed_work.get("referenced_works", []) or []:
                    work_id = to_work_id(ref_id)
                    if not work_id or work_id == res.work_id:
                        continue
                    backward_work_ids.add(work_id)
                    work_to_seed_ids[work_id].append(res.seed_id)
                    edge_map[work_id].add("backward")
        except Exception:
            pass

        try:
            forward = fetch_forward_citations(
                res.work_id,
                max_forward_per_seed=args.max_forward_per_seed,
                timeout_sec=args.request_timeout_sec,
                sleep_sec=args.sleep_sec,
            )
            for w in forward:
                wid = to_work_id(w.get("id", ""))
                if not wid or wid == res.work_id:
                    continue
                forward_works_collected.append(w)
                work_to_seed_ids[wid].append(res.seed_id)
                edge_map[wid].add("forward")
        except Exception:
            pass

    forward_by_id = {to_work_id(w.get("id", "")): w for w in forward_works_collected if w.get("id")}
    all_candidate_ids = set(backward_work_ids) | set(forward_by_id.keys())

    unresolved_backward_ids = sorted(wid for wid in backward_work_ids if wid not in forward_by_id)
    fetched_backward_works = fetch_works_by_ids(
        unresolved_backward_ids,
        timeout_sec=args.request_timeout_sec,
        sleep_sec=args.sleep_sec,
    )

    work_by_id: Dict[str, Dict] = dict(forward_by_id)
    for work in fetched_backward_works:
        wid = to_work_id(work.get("id", ""))
        if wid:
            work_by_id[wid] = work

    candidates = []
    for wid in sorted(all_candidate_ids):
        work = work_by_id.get(wid)
        if not work:
            continue
        base = work_to_candidate(work)
        seed_ids = sorted(set(work_to_seed_ids.get(wid, [])))
        edge_types = sorted(edge_map.get(wid, set()))
        base["origin_seed_ids"] = seed_ids
        base["origin_seed_count"] = len(seed_ids)
        base["edge_types"] = edge_types
        base["cross_seed_score"] = len(seed_ids)
        candidates.append(base)

    write_jsonl(output_dir / "candidates.jsonl", candidates)

    summary = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "input_seed_file": str(seed_file),
        "counts": {
            "seed_queries_total": len(seeds),
            "seed_resolved_total": len(resolved),
            "seed_unresolved_total": len(seeds) - len(resolved),
            "candidates_total": len(candidates),
            "candidates_forward_edge": sum(1 for c in candidates if "forward" in c.get("edge_types", [])),
            "candidates_backward_edge": sum(1 for c in candidates if "backward" in c.get("edge_types", [])),
            "candidates_cross_seed_ge_2": sum(1 for c in candidates if c.get("cross_seed_score", 0) >= 2),
            "candidates_cross_seed_ge_3": sum(1 for c in candidates if c.get("cross_seed_score", 0) >= 3),
        },
        "seed_resolution_breakdown": dict(
            sorted(Counter(r.match_reason for r in resolutions).items(), key=lambda kv: kv[0])
        ),
        "seed_kind_breakdown": dict(
            sorted(Counter(s.get("seed_kind", "") for s in seeds).items(), key=lambda kv: kv[0])
        ),
    }
    write_json(output_dir / "summary.json", summary)
    print(json.dumps(summary["counts"], indent=2))


if __name__ == "__main__":
    main()
